# Generated by Django 2.2.17 on 2025-08-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='country_region_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['population'], name='country_population_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='region_name_idx'),
        ),
    ]
