# Generated by Django 2.2.17 on 2025-08-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20250831_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='topLevelDomain',
            field=models.TextField(default='[]'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['capital'], name='country_capital_idx'),
        ),
    ]
